### PR TITLE
API Endpoints and controllers

### PR DESCRIPTION
**Pull request by devfunsho**
Quick note: I enabled caching, therefore, you will need to change the cache driver to Redis in your .env

### CODE REVIEW

**Comment by AdoraNwodo** [comment]
I get an `Unauthorized` response when I try to create a candidate from Postman.

**Comment by devfunsho** [comment]
@AdoraNwodo I forgot to add. For some endpoints **(PUT /candidate, POST /candiddate, DELETE /candidate)**, you need to set a header **Admin-Key: warpdrive**

**Comment by AdoraNwodo** [comment]
@iamfunsho added the header and it worked! Thanks.

**Review by AdoraNwodo — COMMENTED** [review]
I created a candidate and he had an id of 1. I also created a vote for that candidate and it saved. Now I want to access the candidate's votes using this endpoint - `/candidate/1/votes`
But it returns an empty object

**Comment by devfunsho** [comment]
@AdoraNwodo fixed with the new commit

**Comment by AdoraNwodo** [comment]
@iamfunsho I also looked at `/vote` and in my opinion, vote results are dynamic so I don't feel we should cache them. Same as `/candidate/{id}/vote` and `/candidate`.
What do you think?

**Comment by AdoraNwodo** [comment]
@iamfunsho there is also a CORS issue. Do you want to try using a middleware?

**Comment by devfunsho** [comment]
> @iamfunsho I also looked at `/vote` and in my opinion, vote results are dynamic so I don't feel we should cache them. Same as `/candidate/{id}/vote` and `/candidate`.
> What do you think?

Since we will be doing more of GET than POST requests, this means that visitors will view votes and opinions more than they vote. From my experience managing a high traffic site, once GET > POST requests significantly, it is always best to cache. Also, you don't need to worry about stale content, as I bust the cache once a candidate is created or updated, or a user votes

**Comment by devfunsho** [comment]
> @iamfunsho there is also a CORS issue. Do you want to try using a middleware?

We can take care of CORS at server level. Are we using Nginx?

**Comment by AdoraNwodo** [comment]
> > @iamfunsho I also looked at `/vote` and in my opinion, vote results are dynamic so I don't feel we should cache them. Same as `/candidate/{id}/vote` and `/candidate`.
> > What do you think?
> 
> Since we will be doing more of GET than POST requests, this means that visitors will view votes and opinions more than they vote. From my experience managing a high traffic site, once GET > POST requests significantly, it is always best to cache. Also, you don't need to worry about stale content, as I bust the cache once a candidate is created or updated, or a user votes

Okay then

**Comment by AdoraNwodo** [comment]
> Nginx

Apache

**Comment by devfunsho** [comment]
> > Nginx
> 
> Apache

Chai, can't we find a way to use Nginx? It is super light on system resources and lightening fast.

**Comment by AdoraNwodo** [comment]
> > > Nginx
> > 
> > 
> > Apache
> 
> Chai, can't we find a way to use Nginx? It is super light on system resources and lightening fast.

Okay. Let's do it!

**Comment by devfunsho** [comment]
Nice! Is there anything pending that prevents this merge?

**Comment by AdoraNwodo** [comment]
> Nice! Is there anything pending that prevents this merge?

None. All good now. Issues have been addressed.

**Review by AdoraNwodo — APPROVED** [review]

**Pull request merged**
